- name: Install Java
  package:
    name: java
    state: present

- name: Create Application User
  user:
    name: "{{APP_USER}}"

- name: Download Tomcat
  unarchive:
   src: "{{TOMCAT_URL}}"
   dest: "{{APP_HOME}}"
   remote_src: yes 
  become_user: "{{APP_USER}}"
  notify: Restart Tomcat

- name: Download WAR File
  get_url:
   url: "{{WAR_URL}}"
   dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: "{{APP_USER}}"
  notify: Restart Tomcat

- name: Download JDBC Jar File
  get_url:
   url: "{{JDBC_URL}}"
   dest: "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
  become_user: "{{APP_USER}}"
  notify: Restart Tomcat

- name: Copy context.xml file
  template:
    src: context.xml.j2
    dest: "{{TOMCAT_HOME}}/conf/context.xml"
  become_user: "{{APP_USER}}"
  notify: Restart Tomcat
  
- name: Download tomcat init script
  get_url:
   url: "{{TOMCAT_INIT_URL}}"
   dest: /etc/init.d/tomcat
   mode: "0755"
  notify: Reload systemctl daemon

- name: Start Tomcat service
  service:
   name: tomcat
   state: started
   enabled: yes




