- name: Install web and app severs
  hosts: localhost
  become: yes
  roles:
   - webserver
   - appserver
<<<<<<< HEAD
   - dbserver
   #- newrelic
=======
   #- newrelic
>>>>>>> 8e3b0903a03357cc74f05a01210bd48d059983a6
