- name: Check Pre-reqs
  include_role:
   name: pre-reqs
   tasks_from: check

- name: Load CentOS Play
  include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Load Ubuntu Play
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  