- name: Install Apache2
  apt:
   name: apache2
   state: present
   update_cache: yes
  notify: Restart APACHE2

- name: Install Reverse Proxy Modules 
  shell: a2enmod {{item}}
  loop: ["proxy", "proxy_http", "proxy_balancer", "lbmethod_byrequests"]

- name: Update proxy config
  copy:
   src: proxy-ubuntu.conf
   dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart APACHE2

- name: Download default index file 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html/index.html
    force: yes

- name: Start Service 
  service:
    name: apache2 
    state: started 
    enabled: yes
